### ISSUE TITLE
MPVリリース：レビュー依頼

### ISSUE THREAD

**Issue by SabaCrevette** [SabaCrevette/travel_app#159]
お世話になっております。
MVPリリースのレビュー依頼を提出いたします。

ご確認よろしくお願い致します。

---

## 各種情報
サービス名：PictoMemory
サービスURL：https://pictomemory.com/

### 実装予定の機能（MVP時点）
- [x] ユーザーセッション関連
  - [x] 新規登録
  - [x] ログイン機能
  - [x] ゲストログイン（非ログインユーザーは投稿の閲覧ができるようにしてあります。）
- [x] 都道府県の色塗り機能
  - [x] 観光地の投稿機能
  - [x] 観光地の投稿編集機能
  - [x] 観光地の投稿削除機能
  - [x] ブックマーク機能
  - [x] minimagick等を用いた画像処理
  - [x] ~~ActiveStorageを用いた画像の保存~~ →carrierwaveに変更いたしました
  - [x] 本番環境での画像保存先のストレージの設定（AmazonS3）
  - [x] タグの設定機能
  - [x] 投稿件数に応じた地図の色分け（投稿した各都道府県の件数（0件〜3件以上）で段階的に色味が変わります）
- [x] 都道府県の検索機能
  - [x] 検索項目
    - [x] 都道府県単位
    - [x] タグ検索
    - [x] 観光地の開催時期を検索対象外にする機能
    - [x] 未踏破の都道府県に検索結果を絞る機能
- [x] 投稿お気に入り機能
- [x] Xシェア機能

## READMEレビュー時から変更した機能
- [x] GeocodingAPIの割り当て（本リリース→MVPに前倒しで実装しました）
  - [x] 投稿の「都道府県(prefecture_id)」と「観光地名(location)」の値を用いてAPIを叩き、取得した住所を「address」に保存
  - [x]  取得したlatitude、longitudeによりGoogleMapを表示
- [x] 都道府県を4分割し、各都道府県内からさらに絞って検索
  - [x] postテーブルのprefecture_idと取得したaddressからarea_mappingテーブルを介して市区町村が一致するarea_id（茨城・県央、茨城・県西など）をpostsテーブルに登録するようにしました。
  - [x] 投稿検索でのエリア検索実装（都道府県を選択するとプルダウン解除されます）

## サービスイメージがわかるようなスクリーンショット等
- TOPページ
[![Image from Gyazo](https://i.gyazo.com/88688877e15eb894410cf6c83a7b14da.gif)](https://gyazo.com/88688877e15eb894410cf6c83a7b14da)

[![Image from Gyazo](https://i.gyazo.com/107e2a61a92681b99b1d20f41889c4f1.png)](https://gyazo.com/107e2a61a92681b99b1d20f41889c4f1)

- 投稿一覧 / 検索ページ
[![Image from Gyazo](https://i.gyazo.com/525e10ee6e7e180b8a178c9eb4b9cd2e.png)](https://gyazo.com/525e10ee6e7e180b8a178c9eb4b9cd2e)

- 投稿による色塗り結果確認（マイページ）
[![Image from Gyazo](https://i.gyazo.com/385397f8f6a0994e5c492c909ad2a0ae.png)](https://gyazo.com/385397f8f6a0994e5c492c909ad2a0ae)

**Comment by ooooose** [comment]
@SabaCrevette 
MVPリリースに記載された内容が実装できていることを確認しました。
LGTMです！

**Comment by SabaCrevette** [comment]
ご確認頂きありがとうございました！
引き続き本リリースに向けて開発を続けてまいります。
