### ISSUE TITLE
"issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by SabaCrevette** [SabaCrevette/travel_app#7]
issueを作成いたしました。
ご確認の程よろしくお願いいたします。

[Projects](https://github.com/users/SabaCrevette/projects/7)

## 概要
- issueの作成と提出
- ストーリーポイントの設定（アプリ開発カリキュラムより引用、4は個人設定）
  - 「1」  文言修正など簡単な修正レベルのタスク
  - 「2」  バグ修正や簡単な機能追加レベルのタスク（機能のついていない`view`の作成）
  - 「3」  実装が想像できる通常の機能レベルのタスク（機能の実装）
  - 「4」  実装にあたって難易度の高いもの（5以上に相当）するものを分解したタスク、または3を超える未経験タスク
  - 「5」  実装を進める上で少し調査が必要であったり詰まりそうなタスク（Backlogでの使用を想定、Todoに移す前に4以下に分解する）

### 実装予定の機能（MVP時点）
- [ ] ユーザーセッション関連
  - [ ] 新規登録
  - [ ] ログイン機能
  - [ ] ゲストログイン
- [ ] 都道府県の色塗り機能
  - [ ] 観光地の投稿機能
  - [ ] 観光地の投稿編集機能
  - [ ] 観光地の投稿削除機能
  - [ ] minimagick等を用いた画像処理
  - [ ] ActiveStorageを用いた画像の保存
  - [ ] 本番環境での画像保存先のストレージの設定
  - [ ] タグの設定機能
  - [ ] 投稿件数に応じた地図の色分け
- [ ] 都道府県の検索機能
  - [ ] 検索項目
    - [ ] 都道府県単位
    - [ ] タグ検索
    - [ ] 観光地の開催時期を検索対象外にする機能
    - [ ] 未踏破の都道府県に検索結果を絞る機能
- [ ] 投稿お気に入り機能
- [ ] Xシェア機能

### 必要なページ
- [ ] トップページ
- [ ] ユーザーセッション関連
  - [ ] 新規登録
  - [ ] ログインページ
  - [ ] パスワード再設定のためのアドレス入力ページ
  - [ ] パスワードの再設定
- [ ] お問い合わせ
- [ ] 利用規約
- [ ] プライバシーポリシー
- [ ] マイページ関連
  - [ ] マイページ
  - [ ] プロフィール
  - [ ] パスワード変更
  - [ ] Email変更
- [ ] 投稿関連
  - [ ] 投稿ページ
  - [ ] 投稿詳細ページ
  - [ ] 投稿詳細編集ページ
- [ ] ブックマーク
- [ ] 旅行先検索ページ

**Comment by beppumasaki** [comment]
いいと思います！LGTMです！

**Comment by SabaCrevette** [comment]
- RUNTEQ連携確認のため再度open、再close
